version: '3.8'

services:
  # FastAPI Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: movie-explorer-api
    ports:
      - "8000:80"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount database directory for persistence
      - ./backend/data:/code/data
      # Mount for development (optional - comment out for production)
      - ./backend/app:/code/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:80/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - movie-explorer-network

  # React Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Point frontend to backend service through compose network DNS
        - VITE_API_BASE_URL=http://backend:80
    container_name: movie-explorer-web
    depends_on:
      - backend
    ports:
      - "5173:80"
    environment:
      # Optional override at runtime (takes precedence over build arg if provided)
      - VITE_API_BASE_URL=http://backend:80
    restart: unless-stopped
    networks:
      - movie-explorer-network

networks:
  movie-explorer-network:
    driver: bridge

volumes:
  movie-data:
